add optional self consistency
camel-ai/alpha-craft pull request #1
Opened 2024-12-06 09:52 UTC by depshad

Added self consistency as a boolean parameter (If we have token budget)
From https://arxiv.org/abs/2407.01476, _We also observe that
self-consistency is essential for the performance of search (28.5% → 37.0%)._ 
Reference: https://github.com/kohjingyu/search-agents/blob/main/agent/value_function.py
I could not find the sampling option in chat agent(same as openai so used a for loop). Can someone share how to do that?

2024-12-06 14:18 UTC, SgtVincent commented
Thanks Ekansh for adding this nice feature. 

@richielo Could you please have a look at this update since this is on the file you created?

2024-12-06 19:06 UTC, richielo requested changes

2024-12-06 19:06 UTC, richielo commented on mcts_action/demo/vf_agent.py
> +            return np.mean(all_scores)
Can we get the option to do majority voting too instead of just mean?

2024-12-08 12:20 UTC, depshad commented on mcts_action/demo/vf_agent.py
> +            return np.mean(all_scores)
Added the MAJORITY_VOTE

2024-12-08 13:23 UTC, richielo approved these changes

2024-12-08 14:39 UTC, SgtVincent commented
LGTM! Thanks guys!

2024-12-08 14:39 UTC, merged